### ISSUE TITLE
Don't need to push the venv folder!

### ISSUE THREAD

**Issue by a-rosenberg** [picsul/short-message-survey#1]
you can do a `git rm -rf ./venv` from the main folder to remove the virtual environment and the copy of python from the repository.  Followed by a commit/push, it will be removed from the branch head.

It's typically assumed that a `requirements.txt` is passed and that the person will use their own 
version of Python (or `venv` if they choose so!).  Especially if there are a growing number of requirements, the virtual environment can get quite big.

**Comment by VKrishna04** [comment]
No i want a solution where i  package and give the other person everything they need to run my project including the python and the venv since many people dont even have python or pip in their paths and the python can be in any place in their whole c drive with microsoft pushing to use onedrive ad automatically transfering a few things to onedrive its becoming annoying.
